server:
  port: 8080
  #应用的名称，可选
spring:
  cache:
    redis:
      time-to-live: 1800000 #缓存有效期
  application:
    name: orangemall
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test02?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 1234
  redis:
    host: localhost
    port: 6379
    database: 0
    jedis:
      pool:
        max-wait: 1ms
        max-active: 8
        max-idle: 4
        min-idle: 0

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: delete #全局逻辑删除的实体字段名（since 3.3.0,配置后可以忽略不配置@TableLogic）
      logic-delete-value: 1 #逻辑已删除值(默认为1)
      logic-not-delete-value: 0 #逻辑未删除值(默认为0)

#记得将请求放行
management:
  endpoint:
    health:
      show-details: always


orange:
  path: D:\code\IntelliJ IDEA 2022.2.2\projectDemo\mavenproject\myorangemall\src\main\resources\backend\picture\







